name: sup
description: Personal Journal Companion by Talor Anderson

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.20.4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  english_words: ^3.1.5
  cupertino_icons: ^0.1.2
  cloud_firestore:
  cloud_functions: 0.5.0
  firebase_core: ^0.5.0
  firebase_auth: 0.15.4
  firebase_messaging: ^7.0.0
  firebase_storage: ^3.0.3
  provider:
  intl:
  date_util: 0.1.4
  flutter_calendar_carousel:
  rxdart:
  carousel_slider: ^1.3.0
  bloc:
  menu: ^0.1.4
  flutter_inner_drawer: ^0.5.4
  keyboard_actions: ^3.2.0
  shared_preferences:
  flutter_launcher_icons: "^0.7.3"
  font_awesome_flutter: ^8.11.0
  image_picker: ^0.6.7+22
  share:

dependency_overrides:
  firebase_core: 0.4.4
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/sup_icon.png"
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/img/open-doodles/png/PlantDoodle.png
    - assets/img/open-doodles-dark/png/PlantDoodle.png
    - assets/img/open-doodles/png/MessyDoodle.png
    - assets/img/open-doodles-dark/png/MessyDoodle.png
    - assets/img/open-doodles/png/FloatDoodle.png
    - assets/img/open-doodles-dark/png/FloatDoodle.png
    - assets/img/open-doodles/png/SwingingDoodle.png
    - assets/img/open-doodles-dark/png/SwingingDoodle.png
    - assets/img/open-doodles/png/DoogieDoodle.png
    - assets/img/open-doodles-dark/png/DoogieDoodle.png
    - assets/img/open-doodles/png/DogJumpDoodle.png
    - assets/img/open-doodles-dark/png/DogJumpDoodle.png
    - assets/img/open-doodles/png/DancingDoodle.png
    - assets/img/open-doodles-dark/png/DancingDoodle.png
    - assets/img/open-doodles/png/PettingDoodle.png
    - assets/img/open-doodles-dark/png/PettingDoodle.png
    - assets/img/open-doodles/png/ReadingSideDoodle.png
    - assets/img/open-doodles-dark/png/ReadingSideDoodle.png
    - assets/img/open-doodles/png/SleekDoodle.png
    - assets/img/open-doodles-dark/png/SleekDoodle.png
    - assets/img/open-doodles/png/ReadingDoodle.png
    - assets/img/open-doodles-dark/png/ReadingDoodle.png
    - assets/img/open-doodles/png/UnboxingDoodle.png
    - assets/img/open-doodles-dark/png/UnboxingDoodle.png
    - assets/img/open-doodles/png/SitReadingDoodle.png
    - assets/img/open-doodles-dark/png/SitReadingDoodle.png
    - assets/img/open-doodles/png/MoshingDoodle.png
    - assets/img/open-doodles-dark/png/MoshingDoodle.png
    - assets/img/open-doodles/png/MeditatingDoodle.png
    - assets/img/open-doodles-dark/png/MeditatingDoodle.png
    - assets/img/open-doodles/png/IceCreamDoodle.png
    - assets/img/open-doodles-dark/png/IceCreamDoodle.png
    - assets/img/open-doodles/png/GroovyDoodle.png
    - assets/img/open-doodles-dark/png/GroovyDoodle.png
    - assets/img/open-doodles/png/BalletDoodle.png
    - assets/img/open-doodles-dark/png/BalletDoodle.png
    - assets/img/open-doodles/png/CoffeeDoddle.png
    - assets/img/open-doodles-dark/png/CoffeeDoddle.png
    - assets/img/open-doodles/png/StrollingDoodle.png
    - assets/img/open-doodles-dark/png/StrollingDoodle.png
    - assets/img/open-doodles/png/RollingDoodle.png
    - assets/img/open-doodles-dark/png/RollingDoodle.png
    - assets/img/open-doodles/png/DumpingDoodle.png
    - assets/img/open-doodles-dark/png/DumpingDoodle.png
    - assets/img/open-doodles/png/SprintingDoodle.png
    - assets/img/open-doodles-dark/png/SprintingDoodle.png
    - assets/img/open-doodles/png/BikiniDoodle.png
    - assets/img/open-doodles-dark/png/BikiniDoodle.png
    - assets/img/open-doodles/png/ZombieingDoodle.png
    - assets/img/open-doodles-dark/png/ZombieingDoodle.png
    - assets/img/open-doodles/png/GroovySittingDoodle.png
    - assets/img/open-doodles-dark/png/GroovySittingDoodle.png
    - assets/img/open-doodles/png/SelfieDoodle.png
    - assets/img/open-doodles-dark/png/SelfieDoodle.png
    - assets/img/open-doodles/png/SittingDoodle.png
    - assets/img/open-doodles-dark/png/SittingDoodle.png
    - assets/img/open-doodles/png/RunningDoodle.png
    - assets/img/open-doodles-dark/png/RunningDoodle.png
    - assets/img/open-doodles/png/RollerSkatingDoodle.png
    - assets/img/open-doodles-dark/png/RollerSkatingDoodle.png
    - assets/img/open-doodles/png/LovingDoodle.png
    - assets/img/open-doodles-dark/png/LovingDoodle.png
    - assets/img/open-doodles/png/LayingDoodle.png
    - assets/img/open-doodles-dark/png/LayingDoodle.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
